version: '2'

services:
  shop:
      image: "romas/shop:latest"
      ports:
        - 80:9000
      depends_on:
            - warehouse
  warehouse:
    image: "romas/warehouse:latest"
    ports:
      - 9001:9001
      depends_on:
            -jwt
  jwt:
    image: "romas/jwt:latest"
    ports:
      - 9003:9003