package lt.ws.mif;

/**
 * Created by Romas on 5/7/2017.
 */
public enum ItemStateInWarehouse {
    ITEM_WITH_ALREADY_EXIST, ITEM_DELETED_FROM_DATABASE, ITEM_UPDATED,ITEM_NOT_FOUND, FAILED_ADD_ITEM_TO_WAREHOUSE, ITEM_ADDED_TO_WAREHOUSE
}
