package lt.ws.mif;

/**
 * Created by Romas on 4/22/2017.
 */
public enum ItemState {
    ITEM_ADDED_TO_DATABSE, ITEM_ALREADY_EXIST, ITEM_DELETED_FROM_DATABASE, ITEM_NOT_FOUND, ITEM_UPDATED, RETURNED_TO_WAREHOUSE, CANT_RETURN_ITEM
}
